name: lunchPickerReactNative CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12'
    - run: yarn
    - run: yarn run test
      env:
        REACT_NATIVE_SENTRY_DSN: ${{ secrets.REACT_NATIVE_SENTRY_DSN }}
        REACT_NATIVE_STRIPE_TEST_API_KEY: ${{ secrets.REACT_NATIVE_STRIPE_TEST_API_KEY }}
        REACT_NATIVE_STRIPE_API_KEY: ${{ secrets.REACT_NATIVE_STRIPE_API_KEY }}

